### ISSUE TITLE
[get-pypi-statistics]List index out of  bound error when using the all argument

### ISSUE THREAD

**Issue by bobhancock** [zencore-cn/zencore-issues#1]
When I run it with 'all'argument, I receive the error below. This is run with Python 3.8.3.

get-pypi-statistics 
Usage: get-pypi-statistics [OPTIONS] COMMAND [ARGS]...

  Get statistics of pypi.org. How many projects, how many releases, how many
  files and how many users?

Options:
  --help  Show this message and exit.

Commands:
  all       Get how many projects, release, files and users on pypi.org.
  files     Get how many files on pypi.org.
  projects  Get how many projects on pypi.org.
  releases  Get how many releases on pypi.org.
  users     Get how many users on pypi.org.
bob@rwhp:~$ get-pypi-statistics all
Traceback (most recent call last):
  File "/home/bob/.pyenv/versions/3.8.3/bin/get-pypi-statistics", line 11, in <module>
    load_entry_point('get-pypi-statistics==0.1.0', 'console_scripts', 'get-pypi-statistics')()
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bob/.pyenv/versions/3.8.3/lib/python3.8/site-packages/get_pypi_statistics.py", line 55, in all
    projects = int(results[0].replace(b",", b"").decode())
IndexError: list index out of range

**Comment by zencore-cn** [comment]
@bobhancock Thanks for reporting the issue. I have fixed the problem in version 0.1.1.

The error raised because the site's html changed a litter, and our regex pattern failed to extract the data. Now it's fixed.
